name: iOvergaard
markdown: redcarpet
pygments: true
permalink: /:title.html
author: Jacob Overgaard
author_profile: https://plus.google.com/+JacobOvergaardInfo
exclude: [sass, node_modules, Gemfile, Gemfile.lock, Gruntfile.js, package.json]
include: [.nojekyll]